# Site settings
title: Cybersecurity Sacramento (DC916)
description: Belonging is the very best thing there is
url: https://dc916.com
baseurl: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Theme customization
show_downloads: false

# Collections
collections:
  resources:
    output: true
    permalink: /resources/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# GitHub Pages settings
repository: CyberSecSacramento/Cybersecurity-Sacramento
